### PR TITLE
Gh 66 substituting for internal members

### LINKED ISSUE #66: Detect substituting for `internal` members without `InternalsVisibleTo`
From https://github.com/nsubstitute/NSubstitute/issues/496, having a test assembly with visibility of internal members of assembly under test, but without `InternalsVisibleTo("DynamicProxyGenAssembly2")`, causes errors when running the tests.

It would be good to catch this case, similar to NS2003.

From Robert's comment on NSubstitute@496:

> Referring to [NS2003](https://github.com/nsubstitute/NSubstitute.Analyzers/blob/dev/documentation/rules/NS2003.md), there are no checks on members, only on the type itself. This is the analyzer method in question [AnalyzeTypeAccessability](https://github.com/nsubstitute/NSubstitute.Analyzers/blob/e0edb931c9a0ca3aba1dcb11f5443252ae37c8be/src/NSubstitute.Analyzers.Shared/DiagnosticAnalyzers/AbstractSubstituteAnalyzer.cs#L259)

The [reproduction on that issue](https://github.com/nsubstitute/NSubstitute/issues/496#issue-405476166) is a good test case to illustrate the problem (just having a type with internal members local to the test assembly with trigger the issue).

I'm not sure what category this should belong to. Could be `NS5xxx` as a general usage problem, although it is also sort of similar to `NS1xxx` which covers non-virtual substitution, although in this case it is a non-substitutable member due to `internal`. The easiest is probably to put it in `NS5xxx`, but maybe we should also consider adapting the `NS1xxx` category to be something to do with "non-substitutable members" and include this?

Draft rule page:
---

# NS2003

<table>
<tr>
  <td>CheckId</td>
  <td>NS????</td>
</tr>
<tr>
  <td>Category</td>
  <td>????</td>
</tr>
</table>

## Cause

Substituting for an internal member of a class without proxies having visibility into internal members.

## Rule description

A violation of this rule occurs when using NSubstitute features like `Returns()`, `Received()` etc. with an internal member of a class, but without giving NSubstitute's proxy assembly access to internal members.

## How to fix violations

There are several ways to fix this:

* change the visibility of the member being tested from `internal` to `public`
* change the visibility of the member being tested from `internal` to `protected internal`
*  expose your type being tested to `DynamicProxyGenAssembly2` using:
````c#
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
````

## How to suppress violations

...

### PR DESCRIPTION
**Pull request by tpodolak**
Closes #66

### CODE REVIEW

**Comment by tpodolak** [comment]
Hi @dtchepak as discussed in https://github.com/nsubstitute/NSubstitute.Analyzers/issues/66 detecting internal member substitution is done as one diagnostic. Additionaly I've changed the category  name to "Non-substitutable member" and also adjusted relevant items in documentation. As far as I can tell (checked on VS2017), changing category name doesnt influence the suppression, so if someone used suppression for with old category name 
````
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Non virtual substitution", "NS1002:Non-virtual setup specification.", Justification = "Reviewed")]
`````
this will still work, even though we recomend now using the new category name. If you have time please double-check that, as otherwise this will be a breaking change

**Comment by dtchepak** [comment]
@tpodolak As far as I can tell from [the documentation](https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2017#suppressmessage-usage), the category name will only be used if there are conflicts with other rule identifiers?

In my test project I can replace the category with `"asdfasdf"`, `""`, or `null` and it will still suppress the error if I have the correct `NSxxxx` code there. So I think this would only be a breaking change if there is something else producing `NSxxxx` errors.

**Comment by tpodolak** [comment]
>If I'm correct about the category only being used in that case, next time we update categories maybe we should just make them all `NSubstitute.Analyzers` to differentiate from anything else that produces `NSxxxx` errors?
Not sure if I understand you correctly, are you suggesting to rename all categories to NSubstitute.Analyzers, or to prefix them all with NSubstitute.Analyzers?

**Comment by dtchepak** [comment]
@tpodolak I'm not sure if it should be a prefix or the full category. I don't really understand what the category is for. We can't suppress based on category? From the MS docs it looks like it may just be used to differentiate conflicting codes?

I've seen categories like `Microsoft.Design` and `Microsoft.Maintainability`, `Microsoft.Design`. Maybe we should have things like `NSubstitute.Usage`, `NSubstitute.ArgumentSpecification` etc?

I really don't know about any of this, I just thought I'd ask the question as I noticed that the category listed in the suppression doesn't seem to make any difference at all, which makes me wonder if it is of any use at all! 😂

**Comment by tpodolak** [comment]
For me, the categories are just logical grouping of similar diagnostics. I would say there are targeting the end users rather anything else. I don't think we can suppress by category so it looks like they are only used in case of conflicts. NSubstitute.Usage, NSubstitute.ArgumentSpecification sounds good for me, definitely better than the current one. Will add an enhancement for that later on. However, I would rather keep the categories so I wouldn't join them all into one

**Comment by dtchepak** [comment]
> Will add an enhancement for that later on. However, I would rather keep the categories so I wouldn't join them all into one

Sounds good 👍

**Pull request merged**
