### PR TITLE
Minor message tweaks

### PR DESCRIPTION
**Pull request by dtchepak**
Some very minor message tweaks. Mainly fixing spacing after a ".", but also ended up tweaking the ctor mismatch messages as well.

### CODE REVIEW

**Comment by tpodolak** [comment]
Can you also fix visual basic resource file? And I think as you changed the messages the tests will be failing now

**Comment by dtchepak** [comment]
@tpodolak Ah of course, sorry! (I just adjusted the messages via the GH online editor rather than doing it properly.) I'll resend the corrected PR once I get a chance.

**Comment by dtchepak** [comment]
@tpodolak Think I've fixed my mistake now. 😅 

That's a surprising amount of work! I'll never ask you for a message change again! 😂 

Is it possible to have a shared dictionary for messages and have per-language dictionaries for just the things that vary? (`virtual` vs. `overridable` for example, or format strings for generic types as `For<T>` vs `For(Of T)`) That may cut down the work a little and also help us to keep the messages in sync ([this one](https://github.com/nsubstitute/NSubstitute.Analyzers/pull/13/files#diff-384e122555ac6f8ba6fd6b3a569c77a2R201) is quite different in the VB version for example).

It may also be worth updating the tests to also use the resource dictionary entries -- I think testing that we have the intended message defined in the resources is more important than double-checking the message wording. I think a single source-of-truth for those is ok. 

I'm happy to try to migrate the tests to this approach if it sounds reasonable? I'm probably missing lots of the details sorry, so please point out any problems with this idea. :)

**Comment by dtchepak** [comment]
By the way, if you're happy with this, please "Squash and merge" into the original PR, then merge GH-1-SubstituteForAnalyzers to as I think it is good to go. 👍 😄

**Comment by tpodolak** [comment]
Shared resource file sounds like a good idea, not sure if .net allows merging resx files, but even if it doesn't we can always "manualy" use the one we are interested in. When it comes to test changes I think we can do it as well, this will save time in the future for sure, although some might say that this is anti-pattern as stated in here https://enterprisecraftsmanship.com/2018/01/30/leaking-domain-knowledge-tests/. Even though feel free to change them, from my perspective advantages outweigh disadvantages in this case.

**Pull request merged**
